---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
  labels:
    istio-injection: enabled
---    
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: rabbitmq
  # Specify if topology objects are placed in other ns than this cluster.
  # annotations:
  #   rabbitmq.com/topology-allowed-namespaces: "my-app"
spec:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  rabbitmq:
          additionalConfig: |
                  default_user = guest
                  default_pass = guest
                  log.console.level = info
                  channel_max = 1700
                  default_user_tags.administrator = true

  service:
    type: LoadBalancer
# ---
# Read about installing topology objects in https://rabbitmq.com/kubernetes/operator/using-topology-operator.html#queues-policies
# Read about queues, consumers and publishers in https://rabbitmq.com/documentation.html
# See examples in https://rabbitmq.com/tutorials/tutorial-one-java.html
