apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loadtester-release
  namespace: test
spec:
  interval: 5m
  targetNamespace: test
  chart:
    spec:
      chart: loadtester
      sourceRef:
        kind: HelmRepository
        name: loadtester-repo
        namespace: test
      interval: 1m
  values:
    replicaCount: 1
