---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nesthw-repo
  namespace: apps
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: apps-auth
  url: https://github.com/leifll/nesthw
