apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: knative
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
    # Knative CRDs must be installed before rest of knative.
    - name: knative-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  prune: true
  validation: client
