---
# Knative CRDs must be installed before rest of knative.
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: knative-crds
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-gateway
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/knative/crds/
  prune: true
  validation: client
  wait: true
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: knative-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: knative-crds
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/knative/resources/
  prune: true
  validation: client
---
