---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rabbitmq
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/rabbitmq/install
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rabbitmq-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: rabbitmq
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/rabbitmq/create-resources
  prune: true
  validation: client
