apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metricsserver-release
  namespace: kube-system
spec:
  interval: 5m
  targetNamespace: kube-system
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metricsserver-repo
        namespace: kube-system
      interval: 1m
  # values:
  #   replicaCount: 1
