---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metricsserver-repo
  namespace: kube-system
spec:
  interval: 10m0s
  url: https://kubernetes-sigs.github.io/metrics-server/
