---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: webflux-hw-repo
  namespace: apps
spec:
  interval: 30s
  ref:
    branch: main
  url: ssh://git@github.com/leifll/webflux-hw
