apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: webflux-hw
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: webflux-hw-repo
  path: ./deployment
  prune: true
  validation: client
